# service desciption
services:

  # draw.io server
  draw-io-server:
    image: jgraph/drawio
    container_name: draw-io-server
    hostname: draw-io-server
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"
      # enable traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      # https endpoint
      - "traefik.http.routers.draw-io-websecure.entrypoints=websecure"
      - "traefik.http.routers.draw-io-websecure.rule=Host(`${DRAW_IO_CONT_URL}`)"
      - "traefik.http.routers.draw-io-websecure.tls=true"
      - "traefik.http.routers.draw-io-websecure.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.draw-io-websecure.service=draw-io-service"
      # services
      - "traefik.http.services.draw-io-service.loadbalancer.server.port=8080"

# networks to use
networks:

  # traefik reverse proxy network
  traefik-net:
    external: true
